  GNU nano 6.2                                                                                                                                                                                                                                            docker-compose.yml                                                                                                                                                                                                                                                      
version: "3.8"
services:
  mongo-db:
    image: mongo:4.4
    container_name: mongo-db
    command: mongod --bind_ip 127.0.0.1,mongo-db
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "print('waited for connection')"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 30s
    networks:
      - fiware-network

  fiware-orion:
    image: fiware/orion:3.11.0
    container_name: fiware-orion
    depends_on:
      - mongo-db
    links:
      - mongo-db
    ports:
      - "1026:1026"
    command: -dbhost mongo-db
    networks:
      - fiware-network

  iot-agent:
    image: fiware/iotagent-json
    container_name: fiware-iot-agent
    depends_on:
      - mongo-db
      - fiware-orion
    ports:
      - "4041:4041"
      - "7896:7896"
    environment:
      - IOTA_CB_HOST=fiware-orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_MONGO_HOST=mongo-db
      - IOTA_TIMESTAMP=true
      - IOTA_DEFAULT_RESOURCE=/iot/json
      - IOTA_LOG_LEVEL=DEBUG
    networks:
      - fiware-network

  crate-db:
    image: crate:latest
    container_name: crate-db
    ports:
      - "4200:4200"
      - "5432:5432"
    command: crate
    volumes:
      - /crate.yml:/usr/share/crate/config/crate.yml
      - crate-data:/data
    networks:
      - fiware-network

  quantumleap:
    image: orchestracities/quantumleap
    container_name: quantumleap
    depends_on:
      - crate-db
      - fiware-orion
    ports:
      - "8668:8668"
    environment:
      - CRATE_HOST=crate-db
      - CRATE_PORT=4200
      - CRATE_DB_USER=crate
      - CRATE_DB_PASS=crate
      - QL_DEFAULT_DB=crate
      - LOGLEVEL=INFO
    networks:
      - fiware-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - fiware-network

volumes:
  grafana-data:
  mongo-data:
  crate-data:
networks:
  fiware-network:
    driver: bridge
